@startuml

title __GENETICCODE's Class Diagram__\n

  package com.company {
    package com.company.com.m2i.poe {
      package com.company.com.m2i.poe.Genetic {
        package com.company.com.m2i.poe.GeneticCode {
          class ARN {
              - brin : ArrayList<Base>
              + getBrin()
              + setBrin()
              + ARN()
          }
        }
      }
    }
  }
  

  package com.company {
    package com.company.com.m2i.poe {
      package com.company.com.m2i.poe.Genetic {
        package com.company.com.m2i.poe.GeneticCode {
          class AminoAcid {
              - symbol : String
              - name : String
              + AminoAcid()
              + getSymbol()
              + getName()
              + toString()
          }
        }
      }
    }
  }
  

  package com.company {
    package com.company.com.m2i.poe {
      package com.company.com.m2i.poe.Genetic {
        package com.company.com.m2i.poe.GeneticCode {
          class Base {
              - symbol : String
              - name : String
              - family : String
              + Base()
              + Base()
              + getSymbol()
              + getName()
              + getFamily()
              + toString()
              + getComplementary()
          }
        }
      }
    }
  }
  

  package com.company {
    package com.company.com.m2i.poe {
      package com.company.com.m2i.poe.Genetic {
        package com.company.com.m2i.poe.GeneticCode {
          class Main {
              {static} + main()
          }
        }
      }
    }
  }
  

  package com.company {
    package com.company.com.m2i.poe {
      package com.company.com.m2i.poe.Genetic {
        package com.company.com.m2i.poe.GeneticCode {
          class Protein {
              - chain : ArrayList<AminoAcid>
              + getChain()
          }
        }
      }
    }
  }
  

  package com.company {
    package com.company.com.m2i.poe {
      package com.company.com.m2i.poe.Genetic {
        package com.company.com.m2i.poe.GeneticCode {
          class Ribosome {
              {static} - codonMap : HashMap<String, String>
              + getCodonList()
              + translate()
          }
        }
      }
    }
  }
  

  package com.company {
    package com.company.com.m2i.poe {
      package com.company.com.m2i.poe.Genetic {
        package com.company.com.m2i.poe.GeneticCode {
          class SADN {
              - brin : ArrayList<Base>
              + getBrin()
              + SADN()
              + SADN()
              + toString()
              + getComplementary()
              + getARN()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
